honeybadger_api_key: 'notset'
googleapps_analytics_secret: 'notset'
googleapps_analytics: 'notset'
googleapps_analytics_limit: 10000
googleapps_traffic_start: '2007-02-23'
panda_start: '2011-02-28'
session_token: '123456789012345678901234567890'
display_percentiles: [99,90,75,50]
display_percentiles_labels: ['99th percentile','90th percentile', '75th percentile', '50th percentile']
recent_weeks: 4
flat_percentage: 0.025
# mysql group concat size for percentiles
group_concat_max_len: 1048576
geoip_data_file: 'notset'
