googleapps_analytics_secret: 'notset'
googleapps_analytics: 'notset'
googleapps_search_segments: 
  googlesearch: 'notset'
  us_googlesearch: 'notset'
googleapps_analytics_limit: 10000
googleapps_traffic_start: '2007-02-23'
panda_start: '2011-02-28'
session_token: '123456789012345678901234567890'
darmok_site: 'http://www.extension.org'