googleapps_analytics_secret: 'notset'
googleapps_analytics: 'notset'
googleapps_analytics_limit: 10000
googleapps_traffic_start: '2007-02-23'
panda_start: '2011-02-28'
session_token: '123456789012345678901234567890'
default_percentiles: <%= [10,25,50,75,90,95,99] %>
